server:
  port: 8081

spring:
  application:
    name: customer
  boot:
    admin:
      client:
        url: http://admin:9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka