version: "3.8"
services:

  # MongoDB
  mongo-product:
    image: mongo
    container_name: mongo-product
    ports:
      - "27017:27017"
    networks:
      - ecommerce

  mongo-order:
    image: mongo
    container_name: mongo-order
    ports:
      - "27018:27017"
    networks:
      - ecommerce

  mongo-inventory:
    image: mongo
    container_name: mongo-inventory
    ports:
      - "27020:27017"
    networks:
      - ecommerce

  mongo-payment:
    image: mongo
    container_name: mongo-payment
    ports:
      - "27021:27017"
    networks:
      - ecommerce

  # Kafka & Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ecommerce

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - ecommerce

  # Microservices
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce

  # API Gateway
  apigateway:
    build: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ecommerce

  customer:
    build: ./customer
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - apigateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ecommerce

  product:
    build: ./product
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - apigateway
      - mongo-product
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-product:27017/productdb
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ecommerce

  order:
    build: ./order
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - apigateway
      - mongo-order
      - kafka
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-order:27017/orderdb
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - ecommerce

  inventory:
    build: ./inventory
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - apigateway
      - mongo-inventory
      - kafka
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-inventory:27017/inventorydb
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - ecommerce

  payment:
    build: ./payment
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - apigateway
      - mongo-payment
      - kafka
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-payment:27017/paymentdb
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - ecommerce

networks:
  ecommerce:
