spring:
  application:
    name: product
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  boot:
    admin:
      client:
        url: http://admin:9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8082

inventory:
  service:
    url: http://inventory:8084/
    user: admin
    key: admin

resilience4j:
  circuitbreaker:
    instances:
      productServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka