spring:
  application:
    name: product
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

server:
  port: 8082

inventory:
  service:
    url: http://inventory:8084/
    user: admin
    key: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka